"""AI Content Labeling Service."""

import logging
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum

from models.model import Message
from extensions.ext_database import db

logger = logging.getLogger(__name__)


class AIContentType(Enum):
    """Types of AI-generated content."""
    TEXT = "text"
    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"


class AILabelingService:
    """Service for managing AI content labels and identification."""
    
    # Default AI content labels in multiple languages
    DEFAULT_LABELS = {
        'zh': {
            'text_notice': '内容由AI生成，仅供参考',
            'media_notice': '内容由AI生成',
            'warning': 'AI生成内容可能包含错误',
            'watermark_text': 'AI生成'
        },
        'zh-CN': {
            'text_notice': '内容由AI生成，仅供参考',
            'media_notice': '内容由AI生成',
            'warning': 'AI生成内容可能包含错误',
            'watermark_text': 'AI生成'
        },
        'en': {
            'text_notice': 'Content generated by AI, for reference only',
            'media_notice': 'Content generated by AI',
            'warning': 'AI-generated content may contain errors',
            'watermark_text': 'AI Generated'
        },
        'en-US': {
            'text_notice': 'Content generated by AI, for reference only',
            'media_notice': 'Content generated by AI',
            'warning': 'AI-generated content may contain errors',
            'watermark_text': 'AI Generated'
        },
        'ja': {
            'text_notice': 'AIによって生成されたコンテンツ、参考のみ',
            'media_notice': 'AIによって生成されたコンテンツ',
            'warning': 'AI生成コンテンツには誤りが含まれる可能性があります',
            'watermark_text': 'AI生成'
        },
        'ko': {
            'text_notice': 'AI가 생성한 콘텐츠, 참고용으로만 사용',
            'media_notice': 'AI가 생성한 콘텐츠',
            'warning': 'AI 생성 콘텐츠에는 오류가 포함될 수 있습니다',
            'watermark_text': 'AI 생성'
        },
        'fr': {
            'text_notice': 'Contenu généré par IA, à titre de référence seulement',
            'media_notice': 'Contenu généré par IA',
            'warning': 'Le contenu généré par IA peut contenir des erreurs',
            'watermark_text': 'Généré par IA'
        },
        'de': {
            'text_notice': 'Von KI generierter Inhalt, nur zur Information',
            'media_notice': 'Von KI generierter Inhalt',
            'warning': 'KI-generierte Inhalte können Fehler enthalten',
            'watermark_text': 'KI-generiert'
        },
        'es': {
            'text_notice': 'Contenido generado por IA, solo para referencia',
            'media_notice': 'Contenido generado por IA',
            'warning': 'El contenido generado por IA puede contener errores',
            'watermark_text': 'Generado por IA'
        },
        'pt': {
            'text_notice': 'Conteúdo gerado por IA, apenas para referência',
            'media_notice': 'Conteúdo gerado por IA',
            'warning': 'Conteúdo gerado por IA pode conter erros',
            'watermark_text': 'Gerado por IA'
        },
        'ru': {
            'text_notice': 'Контент создан ИИ, только для справки',
            'media_notice': 'Контент создан ИИ',
            'warning': 'Контент, созданный ИИ, может содержать ошибки',
            'watermark_text': 'Создано ИИ'
        }
    }
    
    def get_ai_labels(self, language: str = 'en') -> Dict[str, str]:
        """
        Get AI content labels for specified language.
        
        Args:
            language: Language code (e.g., 'en', 'zh', 'ja')
            
        Returns:
            Dictionary with label texts in specified language
        """
        # Try exact language match first
        if language in self.DEFAULT_LABELS:
            return self.DEFAULT_LABELS[language]
        
        # Try base language (e.g., 'zh' for 'zh-CN')
        base_lang = language.split('-')[0]
        if base_lang in self.DEFAULT_LABELS:
            return self.DEFAULT_LABELS[base_lang]
        
        # Fallback to English
        return self.DEFAULT_LABELS['en']
    
    def detect_ai_content(
        self,
        content: str,
        model_provider: Optional[str] = None,
        model_id: Optional[str] = None,
        content_type: AIContentType = AIContentType.TEXT
    ) -> bool:
        """
        Detect if content is generated by AI.
        
        Args:
            content: Content to analyze
            model_provider: Provider name (e.g., 'openai', 'anthropic')
            model_id: Model identifier
            content_type: Type of content
            
        Returns:
            True if content is detected as AI-generated
        """
        # For this implementation, we'll use model provider/id to determine AI content
        # In a more sophisticated system, this could use ML models for detection
        
        # If model provider is specified, it's likely AI-generated
        if model_provider:
            ai_providers = {
                'openai', 'anthropic', 'google', 'cohere', 'mistral',
                'claude', 'gpt', 'palm', 'bard', 'llama', 'vicuna'
            }
            
            provider_lower = model_provider.lower()
            if any(ai_provider in provider_lower for ai_provider in ai_providers):
                return True
        
        # If model_id contains AI-related keywords
        if model_id:
            ai_keywords = {
                'gpt', 'claude', 'palm', 'bard', 'llama', 'vicuna',
                'alpaca', 'chatglm', 'baichuan', 'qwen'
            }
            
            model_lower = model_id.lower()
            if any(keyword in model_lower for keyword in ai_keywords):
                return True
        
        # Check content patterns that might indicate AI generation
        if content_type == AIContentType.TEXT:
            return self._detect_ai_text_patterns(content)
        
        return False
    
    def _detect_ai_text_patterns(self, text: str) -> bool:
        """
        Detect AI-generated text patterns.
        
        Args:
            text: Text content to analyze
            
        Returns:
            True if AI patterns are detected
        """
        # Simple pattern detection - in production, this would be more sophisticated
        ai_phrases = {
            'en': [
                'as an ai', 'i am an ai', 'as a language model', 
                'i do not have personal', 'i cannot provide personal',
                'as artificial intelligence', 'i\'m an ai assistant'
            ],
            'zh': [
                '作为ai', '作为人工智能', '我是一个ai', '我是人工智能',
                '作为语言模型', '我无法提供个人', '我不能提供个人'
            ]
        }
        
        text_lower = text.lower()
        
        # Check English patterns
        if any(phrase in text_lower for phrase in ai_phrases['en']):
            return True
        
        # Check Chinese patterns
        if any(phrase in text_lower for phrase in ai_phrases['zh']):
            return True
        
        return False
    
    def create_ai_label_info(
        self,
        model_provider: Optional[str] = None,
        model_id: Optional[str] = None,
        model_version: Optional[str] = None,
        language: str = 'en',
        content_type: AIContentType = AIContentType.TEXT,
        custom_labels: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Create AI labeling information for a message.
        
        Args:
            model_provider: AI model provider name
            model_id: AI model identifier
            model_version: AI model version
            language: User's preferred language
            content_type: Type of content being labeled
            custom_labels: Custom label information
            
        Returns:
            Dictionary with AI labeling information
        """
        labels = self.get_ai_labels(language)
        
        # Create model info
        model_info = {}
        if model_provider:
            model_info['provider'] = model_provider
        if model_id:
            model_info['model_id'] = model_id
        if model_version:
            model_info['version'] = model_version
        
        # Create content labels
        content_labels = {
            'inappropriate': False,
            'generated_content_notice': labels.get('text_notice', labels['text_notice']),
            'media_notice': labels.get('media_notice', labels['media_notice']),
            'watermark_text': labels.get('watermark_text', labels['watermark_text']),
            'watermark_applied': False,
            'language': language,
            'content_type': content_type.value,
            'created_at': datetime.utcnow().isoformat()
        }
        
        # Add custom labels if provided
        if custom_labels:
            content_labels.update(custom_labels)
        
        return {
            'model_info': model_info if model_info else None,
            'content_labels': content_labels
        }
    
    def apply_ai_labeling(
        self,
        message_id: str,
        model_provider: Optional[str] = None,
        model_id: Optional[str] = None,
        model_version: Optional[str] = None,
        language: str = 'en',
        content_type: AIContentType = AIContentType.TEXT,
        force_ai_generated: Optional[bool] = None
    ) -> bool:
        """
        Apply AI labeling to a message.
        
        Args:
            message_id: Message ID to label
            model_provider: AI model provider
            model_id: AI model identifier
            model_version: AI model version
            language: User's preferred language
            content_type: Type of content
            force_ai_generated: Force AI generated flag (override detection)
            
        Returns:
            True if labeling was applied successfully
        """
        try:
            message = db.session.query(Message).filter_by(id=message_id).first()
            if not message:
                logger.warning(f"Message not found: {message_id}")
                return False
            
            # Determine if content is AI-generated
            if force_ai_generated is not None:
                is_ai_generated = force_ai_generated
            else:
                is_ai_generated = self.detect_ai_content(
                    content=message.answer or "",
                    model_provider=model_provider or message.model_provider,
                    model_id=model_id or message.model_id,
                    content_type=content_type
                )
            
            # Update message with AI labeling
            if is_ai_generated:
                label_info = self.create_ai_label_info(
                    model_provider=model_provider or message.model_provider,
                    model_id=model_id or message.model_id,
                    model_version=model_version,
                    language=language,
                    content_type=content_type
                )
                
                message.ai_generated = True
                message.ai_model_info = label_info['model_info']
                message.content_labels = label_info['content_labels']
            else:
                message.ai_generated = False
                message.ai_model_info = None
                message.content_labels = None
            
            message.updated_at = datetime.utcnow()
            db.session.commit()
            
            logger.info(f"Applied AI labeling to message {message_id}: ai_generated={is_ai_generated}")
            return True
            
        except Exception as e:
            db.session.rollback()
            logger.error(f"Failed to apply AI labeling to message {message_id}: {e}", exc_info=True)
            return False
    
    def get_message_labels(self, message_id: str, language: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """
        Get AI labels for a message.
        
        Args:
            message_id: Message ID
            language: Preferred language (for dynamic label updates)
            
        Returns:
            Dictionary with AI label information or None
        """
        try:
            message = db.session.query(Message).filter_by(id=message_id).first()
            if not message or not message.ai_generated:
                return None
            
            labels = message.content_labels.copy() if message.content_labels else {}
            
            # Update labels if different language requested
            if language and labels.get('language') != language:
                new_labels = self.get_ai_labels(language)
                labels.update({
                    'generated_content_notice': new_labels['text_notice'],
                    'media_notice': new_labels['media_notice'],
                    'watermark_text': new_labels['watermark_text'],
                    'language': language
                })
            
            return {
                'ai_generated': message.ai_generated,
                'ai_model_info': message.ai_model_info,
                'content_labels': labels
            }
            
        except Exception as e:
            logger.error(f"Failed to get message labels for {message_id}: {e}", exc_info=True)
            return None
    
    def bulk_apply_labeling(
        self,
        message_ids: List[str],
        model_provider: Optional[str] = None,
        language: str = 'en',
        batch_size: int = 100
    ) -> Dict[str, int]:
        """
        Apply AI labeling to multiple messages in batches.
        
        Args:
            message_ids: List of message IDs
            model_provider: Default model provider
            language: User's preferred language
            batch_size: Number of messages to process per batch
            
        Returns:
            Dictionary with processing statistics
        """
        total_processed = 0
        total_labeled = 0
        total_errors = 0
        
        # Process messages in batches
        for i in range(0, len(message_ids), batch_size):
            batch_ids = message_ids[i:i + batch_size]
            
            try:
                messages = db.session.query(Message).filter(
                    Message.id.in_(batch_ids)
                ).all()
                
                for message in messages:
                    try:
                        is_ai_generated = self.detect_ai_content(
                            content=message.answer or "",
                            model_provider=model_provider or message.model_provider,
                            model_id=message.model_id,
                            content_type=AIContentType.TEXT
                        )
                        
                        if is_ai_generated:
                            label_info = self.create_ai_label_info(
                                model_provider=model_provider or message.model_provider,
                                model_id=message.model_id,
                                language=language
                            )
                            
                            message.ai_generated = True
                            message.ai_model_info = label_info['model_info']
                            message.content_labels = label_info['content_labels']
                            message.updated_at = datetime.utcnow()
                            
                            total_labeled += 1
                        
                        total_processed += 1
                        
                    except Exception as e:
                        logger.error(f"Error processing message {message.id}: {e}")
                        total_errors += 1
                
                db.session.commit()
                
            except Exception as e:
                db.session.rollback()
                logger.error(f"Error processing batch {i//batch_size + 1}: {e}", exc_info=True)
                total_errors += len(batch_ids)
        
        logger.info(f"Bulk labeling completed: {total_processed} processed, {total_labeled} labeled, {total_errors} errors")
        
        return {
            'total_processed': total_processed,
            'total_labeled': total_labeled,
            'total_errors': total_errors
        }
    
    def get_labeling_stats(self) -> Dict[str, Any]:
        """
        Get statistics about AI content labeling.
        
        Returns:
            Dictionary with labeling statistics
        """
        try:
            total_messages = db.session.query(Message).count()
            ai_generated_count = db.session.query(Message).filter(
                Message.ai_generated == True
            ).count()
            
            labeled_count = db.session.query(Message).filter(
                Message.content_labels.isnot(None)
            ).count()
            
            return {
                'total_messages': total_messages,
                'ai_generated_messages': ai_generated_count,
                'labeled_messages': labeled_count,
                'labeling_rate': round(labeled_count / total_messages * 100, 2) if total_messages > 0 else 0,
                'ai_detection_rate': round(ai_generated_count / total_messages * 100, 2) if total_messages > 0 else 0
            }
            
        except Exception as e:
            logger.error(f"Failed to get labeling stats: {e}", exc_info=True)
            return {
                'total_messages': 0,
                'ai_generated_messages': 0,
                'labeled_messages': 0,
                'labeling_rate': 0,
                'ai_detection_rate': 0
            }