"""Tests for AI Labeling Service."""

import pytest
from unittest.mock import patch, MagicMock
from datetime import datetime

from services.ai_labeling_service import AILabelingService, AIContentType
from models.model import Message
from extensions.ext_database import db


class TestAILabelingService:
    """Test AI labeling service functionality."""
    
    def setup_method(self):
        """Set up test method."""
        self.service = AILabelingService()
    
    def test_get_ai_labels_default_language(self):
        """Test getting AI labels for default language."""
        labels = self.service.get_ai_labels('en')
        
        assert 'text_notice' in labels
        assert 'media_notice' in labels
        assert 'watermark_text' in labels
        assert labels['text_notice'] == 'Content generated by AI, for reference only'
    
    def test_get_ai_labels_chinese(self):
        """Test getting AI labels for Chinese."""
        labels = self.service.get_ai_labels('zh')
        
        assert labels['text_notice'] == '内容由AI生成，仅供参考'
        assert labels['watermark_text'] == 'AI生成'
    
    def test_get_ai_labels_fallback_to_base_language(self):
        """Test language fallback to base language."""
        labels = self.service.get_ai_labels('zh-CN')
        
        # Should get zh labels since zh-CN maps to zh
        assert labels['text_notice'] == '内容由AI生成，仅供参考'
    
    def test_get_ai_labels_fallback_to_english(self):
        """Test language fallback to English."""
        labels = self.service.get_ai_labels('unsupported')
        
        # Should fallback to English
        assert labels['text_notice'] == 'Content generated by AI, for reference only'
    
    def test_detect_ai_content_by_provider(self):
        """Test AI content detection by provider."""
        # Test with known AI provider
        is_ai = self.service.detect_ai_content(
            content="Test content",
            model_provider="openai",
            model_id="gpt-4"
        )
        assert is_ai is True
        
        # Test with non-AI provider
        is_ai = self.service.detect_ai_content(
            content="Test content",
            model_provider="custom",
            model_id="local-model"
        )
        assert is_ai is False
    
    def test_detect_ai_content_by_model_id(self):
        """Test AI content detection by model ID."""
        # Test with GPT model
        is_ai = self.service.detect_ai_content(
            content="Test content",
            model_id="gpt-3.5-turbo"
        )
        assert is_ai is True
        
        # Test with Claude model
        is_ai = self.service.detect_ai_content(
            content="Test content",
            model_id="claude-2"
        )
        assert is_ai is True
    
    def test_detect_ai_text_patterns_english(self):
        """Test AI text pattern detection in English."""
        ai_text = "As an AI language model, I cannot provide personal opinions."
        is_ai = self.service.detect_ai_content(ai_text)
        assert is_ai is True
        
        human_text = "I personally think this is a great idea!"
        is_ai = self.service.detect_ai_content(human_text)
        assert is_ai is False
    
    def test_detect_ai_text_patterns_chinese(self):
        """Test AI text pattern detection in Chinese."""
        ai_text = "作为AI助手，我无法提供个人观点。"
        is_ai = self.service.detect_ai_content(ai_text)
        assert is_ai is True
        
        human_text = "我个人认为这是个好主意！"
        is_ai = self.service.detect_ai_content(human_text)
        assert is_ai is False
    
    def test_create_ai_label_info(self):
        """Test creating AI label information."""
        label_info = self.service.create_ai_label_info(
            model_provider="openai",
            model_id="gpt-4",
            model_version="2024-01",
            language="en",
            content_type=AIContentType.TEXT
        )
        
        assert 'model_info' in label_info
        assert 'content_labels' in label_info
        assert label_info['model_info']['provider'] == "openai"
        assert label_info['model_info']['model_id'] == "gpt-4"
        assert label_info['content_labels']['language'] == "en"
        assert label_info['content_labels']['content_type'] == "text"
    
    def test_create_ai_label_info_with_custom_labels(self):
        """Test creating AI label info with custom labels."""
        custom_labels = {
            'custom_field': 'custom_value',
            'watermark_applied': True
        }
        
        label_info = self.service.create_ai_label_info(
            language="zh",
            custom_labels=custom_labels
        )
        
        assert label_info['content_labels']['custom_field'] == 'custom_value'
        assert label_info['content_labels']['watermark_applied'] is True
        assert label_info['content_labels']['language'] == "zh"
    
    @patch('services.ai_labeling_service.db.session')
    def test_apply_ai_labeling_success(self, mock_db_session):
        """Test successful AI labeling application."""
        # Mock message
        mock_message = MagicMock()
        mock_message.id = "test-message-id"
        mock_message.answer = "As an AI, I can help you with that."
        mock_message.model_provider = "openai"
        mock_message.model_id = "gpt-4"
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        # Apply labeling
        success = self.service.apply_ai_labeling(
            message_id="test-message-id",
            language="en"
        )
        
        assert success is True
        assert mock_message.ai_generated is True
        assert mock_message.ai_model_info is not None
        assert mock_message.content_labels is not None
        mock_db_session.commit.assert_called_once()
    
    @patch('services.ai_labeling_service.db.session')
    def test_apply_ai_labeling_message_not_found(self, mock_db_session):
        """Test AI labeling when message not found."""
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = None
        
        success = self.service.apply_ai_labeling("nonexistent-id")
        
        assert success is False
    
    @patch('services.ai_labeling_service.db.session')
    def test_apply_ai_labeling_force_ai_generated(self, mock_db_session):
        """Test forcing AI generated flag."""
        # Mock message
        mock_message = MagicMock()
        mock_message.id = "test-message-id"
        mock_message.answer = "Regular human text."
        mock_message.model_provider = None
        mock_message.model_id = None
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        # Force AI generated
        success = self.service.apply_ai_labeling(
            message_id="test-message-id",
            force_ai_generated=True
        )
        
        assert success is True
        assert mock_message.ai_generated is True
        assert mock_message.ai_model_info is not None
        assert mock_message.content_labels is not None
    
    @patch('services.ai_labeling_service.db.session')
    def test_apply_ai_labeling_not_ai_generated(self, mock_db_session):
        """Test labeling when content is not AI-generated."""
        # Mock message
        mock_message = MagicMock()
        mock_message.id = "test-message-id"
        mock_message.answer = "Regular human text."
        mock_message.model_provider = None
        mock_message.model_id = None
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        success = self.service.apply_ai_labeling("test-message-id")
        
        assert success is True
        assert mock_message.ai_generated is False
        assert mock_message.ai_model_info is None
        assert mock_message.content_labels is None
    
    @patch('services.ai_labeling_service.db.session')
    def test_get_message_labels_success(self, mock_db_session):
        """Test getting message labels successfully."""
        # Mock message
        mock_message = MagicMock()
        mock_message.ai_generated = True
        mock_message.ai_model_info = {"provider": "openai", "model_id": "gpt-4"}
        mock_message.content_labels = {
            "generated_content_notice": "AI generated content",
            "language": "en"
        }
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        labels = self.service.get_message_labels("test-message-id")
        
        assert labels is not None
        assert labels['ai_generated'] is True
        assert labels['ai_model_info']['provider'] == "openai"
        assert labels['content_labels']['generated_content_notice'] == "AI generated content"
    
    @patch('services.ai_labeling_service.db.session')
    def test_get_message_labels_not_ai_generated(self, mock_db_session):
        """Test getting labels for non-AI message."""
        # Mock message
        mock_message = MagicMock()
        mock_message.ai_generated = False
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        labels = self.service.get_message_labels("test-message-id")
        
        assert labels is None
    
    @patch('services.ai_labeling_service.db.session')
    def test_get_message_labels_different_language(self, mock_db_session):
        """Test getting labels with different language."""
        # Mock message
        mock_message = MagicMock()
        mock_message.ai_generated = True
        mock_message.ai_model_info = {"provider": "openai"}
        mock_message.content_labels = {
            "generated_content_notice": "AI generated content",
            "language": "en"
        }
        
        mock_db_session.query.return_value.filter_by.return_value.first.return_value = mock_message
        
        labels = self.service.get_message_labels("test-message-id", "zh")
        
        assert labels is not None
        assert labels['content_labels']['language'] == "zh"
        assert "内容由AI生成" in labels['content_labels']['generated_content_notice']
    
    @patch('services.ai_labeling_service.db.session')
    def test_bulk_apply_labeling(self, mock_db_session):
        """Test bulk AI labeling application."""
        # Mock messages
        messages = []
        for i in range(3):
            mock_message = MagicMock()
            mock_message.id = f"message-{i}"
            mock_message.answer = "As an AI, I can help you."
            mock_message.model_provider = "openai"
            mock_message.model_id = "gpt-4"
            messages.append(mock_message)
        
        mock_db_session.query.return_value.filter.return_value.all.return_value = messages
        
        # Apply bulk labeling
        results = self.service.bulk_apply_labeling(
            message_ids=["message-0", "message-1", "message-2"],
            batch_size=2
        )
        
        assert results['total_processed'] == 3
        assert results['total_labeled'] == 3
        assert results['total_errors'] == 0
        
        # Verify all messages were labeled
        for message in messages:
            assert message.ai_generated is True
            assert message.ai_model_info is not None
            assert message.content_labels is not None
    
    @patch('services.ai_labeling_service.db.session')
    def test_get_labeling_stats(self, mock_db_session):
        """Test getting labeling statistics."""
        # Mock query results
        mock_db_session.query.return_value.count.side_effect = [100, 75, 80]  # total, ai_generated, labeled
        
        stats = self.service.get_labeling_stats()
        
        assert stats['total_messages'] == 100
        assert stats['ai_generated_messages'] == 75
        assert stats['labeled_messages'] == 80
        assert stats['labeling_rate'] == 80.0
        assert stats['ai_detection_rate'] == 75.0
    
    def test_all_supported_languages_have_required_keys(self):
        """Test that all supported languages have required label keys."""
        required_keys = ['text_notice', 'media_notice', 'watermark_text', 'warning']
        
        for language in self.service.DEFAULT_LABELS:
            labels = self.service.get_ai_labels(language)
            for key in required_keys:
                assert key in labels, f"Missing key '{key}' in language '{language}'"
                assert labels[key], f"Empty value for key '{key}' in language '{language}'"