'use client'

import React, { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import ReportButton from './ReportButton'

export interface AILabelInfo {
  ai_generated: boolean
  ai_model_info?: {
    provider?: string
    model_id?: string
    version?: string
  }
  content_labels?: {
    generated_content_notice?: string
    media_notice?: string
    watermark_text?: string
    inappropriate?: boolean
    language?: string
    content_type?: string
    created_at?: string
  }
}

export interface AIContentLabelProps {
  labelInfo?: AILabelInfo
  contentType?: 'text' | 'image' | 'video' | 'audio'
  contentId?: string
  showModelInfo?: boolean
  showIcon?: boolean
  showReportButton?: boolean
  className?: string
  variant?: 'default' | 'compact' | 'minimal'
  position?: 'bottom' | 'top' | 'inline'
}

const AIContentLabel: React.FC<AIContentLabelProps> = ({
  labelInfo,
  contentType = 'text',
  contentId,
  showModelInfo = false,
  showIcon = true,
  showReportButton = true,
  className = '',
  variant = 'default',
  position = 'bottom'
}) => {
  const { t, i18n } = useTranslation()
  const [isExpanded, setIsExpanded] = useState(false)
  const [displayText, setDisplayText] = useState('')

  // Update display text when language or label info changes
  useEffect(() => {
    if (!labelInfo?.ai_generated) {
      setDisplayText('')
      return
    }

    const currentLang = i18n.language
    let text = ''

    if (contentType === 'text') {
      text = labelInfo.content_labels?.generated_content_notice || 
             t('ai.labels.defaultTextNotice', 'Content generated by AI, for reference only')
    } else {
      text = labelInfo.content_labels?.media_notice || 
             t('ai.labels.defaultMediaNotice', 'Content generated by AI')
    }

    setDisplayText(text)
  }, [labelInfo, contentType, i18n.language, t])

  if (!labelInfo?.ai_generated) {
    return null
  }

  const formatModelInfo = () => {
    if (!labelInfo.ai_model_info) return null
    
    const { provider, model_id, version } = labelInfo.ai_model_info
    const parts = []
    
    if (provider) parts.push(provider)
    if (model_id) parts.push(model_id)
    if (version) parts.push(`v${version}`)
    
    return parts.join(' ')
  }

  const getVariantStyles = () => {
    const baseStyles = "flex items-center gap-2 text-sm transition-colors"
    
    switch (variant) {
      case 'compact':
        return `${baseStyles} text-xs py-1 px-2`
      case 'minimal':
        return `${baseStyles} text-xs opacity-70 hover:opacity-100`
      default:
        return `${baseStyles} py-2 px-3`
    }
  }

  const getPositionStyles = () => {
    switch (position) {
      case 'top':
        return 'mb-2'
      case 'inline':
        return 'inline-flex'
      default:
        return 'mt-2'
    }
  }

  const AIIcon = () => (
    <svg 
      className="w-4 h-4 flex-shrink-0" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth={2}
    >
      <path d="M9 12l2 2 4-4" />
      <path d="M21 12c-1 0-3-1-3-3s2-3 3-3 3 1 3 3-2 3-3 3" />
      <path d="M3 12c1 0 3-1 3-3s-2-3-3-3-3 1-3 3 2 3 3 3" />
      <path d="M12 3c0 1-1 3-3 3s-3-2-3-3 1-3 3-3 3 2 3 3" />
      <path d="M12 21c0-1 1-3 3-3s3 2 3 3-1 3-3 3-3-2-3-3" />
    </svg>
  )

  const RobotIcon = () => (
    <svg 
      className="w-4 h-4 flex-shrink-0" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth={2}
    >
      <rect x="3" y="11" width="18" height="10" rx="2" ry="2" />
      <circle cx="12" cy="5" r="2" />
      <path d="m12 7v4" />
      <line x1="8" y1="16" x2="8" y2="16" />
      <line x1="16" y1="16" x2="16" y2="16" />
    </svg>
  )

  return (
    <div className={`
      ${getVariantStyles()} 
      ${getPositionStyles()} 
      ${className}
      bg-blue-50 dark:bg-blue-900/20 
      border border-blue-200 dark:border-blue-800 
      text-blue-700 dark:text-blue-300 
      rounded-md
    `}>
      {showIcon && (
        <div className="text-blue-500 dark:text-blue-400">
          <RobotIcon />
        </div>
      )}
      
      <div className="flex-1 min-w-0">
        <div className="flex items-center justify-between">
          <span className="text-sm font-medium truncate">
            {displayText}
          </span>
          
          {showModelInfo && labelInfo.ai_model_info && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="ml-2 text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-200 focus:outline-none"
              aria-label={isExpanded ? t('common.collapse') : t('common.expand')}
            >
              <svg 
                className={`w-4 h-4 transform transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24"
              >
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
          )}
        </div>
        
        {isExpanded && showModelInfo && (
          <div className="mt-2 pt-2 border-t border-blue-200 dark:border-blue-700">
            <div className="text-xs text-blue-600 dark:text-blue-400 space-y-1">
              {labelInfo.ai_model_info?.provider && (
                <div>
                  <span className="font-medium">{t('ai.labels.provider')}:</span> {labelInfo.ai_model_info.provider}
                </div>
              )}
              {labelInfo.ai_model_info?.model_id && (
                <div>
                  <span className="font-medium">{t('ai.labels.model')}:</span> {labelInfo.ai_model_info.model_id}
                </div>
              )}
              {labelInfo.ai_model_info?.version && (
                <div>
                  <span className="font-medium">{t('ai.labels.version')}:</span> {labelInfo.ai_model_info.version}
                </div>
              )}
              {labelInfo.content_labels?.created_at && (
                <div>
                  <span className="font-medium">{t('ai.labels.generated')}:</span>{' '}
                  {new Date(labelInfo.content_labels.created_at).toLocaleString()}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
      
      {/* Warning indicator for inappropriate content */}
      {labelInfo.content_labels?.inappropriate && (
        <div className="text-amber-500 dark:text-amber-400" title={t('ai.labels.inappropriateWarning')}>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.732-.833-2.5 0L4.268 18.5C3.498 20.333 4.46 22 6 22z" />
          </svg>
        </div>
      )}
      
      {/* Report Button */}
      {showReportButton && contentId && (
        <div className="ml-2">
          <ReportButton
            contentId={contentId}
            contentType={contentType}
            contentSnapshot={labelInfo}
            variant="icon-only"
            position="inline"
            className="text-blue-500 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
          />
        </div>
      )}
    </div>
  )
}

export default AIContentLabel