<script lang="ts">
	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';
	import type { i18n as i18nType } from 'i18next';

	const i18n = getContext<Writable<i18nType>>('i18n');
	
	export let type: 'text' | 'image' | 'video' = 'text';
	export let showLabel = true;
	
	// 根据类型显示不同的标识文本
	$: labelText = type === 'text' 
		? '内容由AI生成，仅供参考' 
		: '内容由AI生成';
	
	$: labelTextEn = type === 'text'
		? 'Content generated by AI, for reference only'
		: 'AI Generated Content';
</script>

{#if showLabel}
	<div class="ai-content-label mt-2 px-3 py-1.5 bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700 rounded-lg">
		<div class="flex items-center gap-2">
			<!-- AI图标 -->
			<svg class="w-4 h-4 text-blue-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.847a4.5 4.5 0 003.09 3.09L15.75 12l-2.847.813a4.5 4.5 0 00-3.09 3.091zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z"/>
			</svg>
			
			<!-- 标识文本 -->
			<span class="text-xs text-gray-600 dark:text-gray-400 font-medium">
				{$i18n.language.startsWith('zh') ? labelText : labelTextEn}
			</span>
		</div>
	</div>
{/if}

<style>
	.ai-content-label {
		font-size: 0.75rem;
		line-height: 1rem;
		user-select: none;
		opacity: 0.9;
		transition: opacity 0.2s ease;
	}
	
	.ai-content-label:hover {
		opacity: 1;
	}
</style>